project_name: pomo

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      # - linux
      # - windows
      - darwin
    

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: pomo-cli
    description: Pomodoro Timer CLI tool
    homepage: https://github.com/codeanish/pomo-cli
    tap:
      owner: codeanish
      name: homebrew-pomo-cli
    commit_author:
      name: codeanish
      email: anish@codeanish.com
    folder: Formula

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
