# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 24px font.
Set FontSize 24
Set Width 1200
Set Height 600
Set PlaybackSpeed 5.0
Set TypingSpeed 1s
Set CursorBlink false

# Type a command in the terminal.
Type "pomo"

# Pause for dramatic effect...
Sleep 3s

# Run the command by pressing enter.
Enter

Type "k"

Sleep 3s

Type "1"

Sleep 3s

Enter

# Admire the output for a bit.
Sleep 65s